SELECT R.CAR_ID,
       R.CAR_TYPE,
       ROUND(DAILY_FEE * 30 * (100 - CAST(REPLACE(DISCOUNT_RATE,'%','') AS SIGNED)) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR R
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
ON R.CAR_TYPE = D.CAR_TYPE
WHERE R.CAR_TYPE IN ('세단','SUV')
AND D.DURATION_TYPE = '30일 이상'

AND R.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30'
    AND END_DATE >= '2022-11-01'
)

AND DAILY_FEE * 30 * (100 - CAST(REPLACE(DISCOUNT_RATE,'%','') AS SIGNED)) / 100 >= 500000
AND DAILY_FEE * 30 * (100 - CAST(REPLACE(DISCOUNT_RATE,'%','') AS SIGNED)) / 100 < 2000000

ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;